# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-24 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('year', models.IntegerField()),
                ('numberOfCitations', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persNo', models.IntegerField()),
                ('firstName', models.TextField()),
                ('lastName', models.TextField()),
                ('position', models.CharField(max_length=100)),
                ('affiliation', models.CharField(max_length=100)),
                ('numberOfPubs', models.IntegerField()),
                ('numberOfCitations', models.IntegerField()),
                ('hIndex', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SubjectArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectName', models.CharField(max_length=100)),
                ('faculty', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('researchers', models.ManyToManyField(to='capstone.Researcher')),
            ],
        ),
        migrations.AddField(
            model_name='publication',
            name='researchers',
            field=models.ManyToManyField(to='capstone.Researcher'),
        ),
    ]
