# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-25 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='id',
        ),
        migrations.RemoveField(
            model_name='researcher',
            name='affiliation',
        ),
        migrations.RemoveField(
            model_name='researcher',
            name='id',
        ),
        migrations.RemoveField(
            model_name='subjectarea',
            name='id',
        ),
        migrations.AddField(
            model_name='publication',
            name='pubID',
            field=models.IntegerField(default=12345, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='researcher',
            name='department',
            field=models.CharField(default='dept', max_length=100),
        ),
        migrations.AddField(
            model_name='researcher',
            name='faculty',
            field=models.CharField(default='faculty', max_length=100),
        ),
        migrations.AddField(
            model_name='subjectarea',
            name='subjectID',
            field=models.IntegerField(default=123, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='persNo',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
