# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-26 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('queueID', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='publication',
            name='id',
        ),
        migrations.RemoveField(
            model_name='researcher',
            name='affiliation',
        ),
        migrations.RemoveField(
            model_name='researcher',
            name='id',
        ),
        migrations.RemoveField(
            model_name='subjectarea',
            name='id',
        ),
        migrations.AddField(
            model_name='publication',
            name='pubID',
            field=models.IntegerField(default=12345, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='researcher',
            name='department',
            field=models.CharField(default='dept', max_length=100),
        ),
        migrations.AddField(
            model_name='researcher',
            name='faculty',
            field=models.CharField(default='fac', max_length=100),
        ),
        migrations.AddField(
            model_name='researcher',
            name='name',
            field=models.TextField(default='potato'),
        ),
        migrations.AddField(
            model_name='subjectarea',
            name='subjectID',
            field=models.IntegerField(default=123, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='persNo',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='subjectarea',
            name='researchers',
        ),
        migrations.AddField(
            model_name='subjectarea',
            name='researchers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='capstone.Researcher'),
        ),
        migrations.AddField(
            model_name='queue',
            name='researchers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capstone.Researcher'),
        ),
    ]
