# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-26 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0002_auto_20171026_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectarea',
            name='researchers',
        ),
        migrations.AddField(
            model_name='researcher',
            name='subjectArea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='capstone.SubjectArea'),
        ),
    ]
