# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-29 05:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0003_auto_20171026_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queueID', models.IntegerField()),
                ('queueNum', models.IntegerField()),
                ('researchers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capstone.Researcher')),
            ],
        ),
        migrations.RemoveField(
            model_name='queue',
            name='researchers',
        ),
        migrations.AlterField(
            model_name='queue',
            name='queueID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='queueitems',
            unique_together=set([('queueID', 'queueNum')]),
        ),
    ]
